CREATE TABLE BUNDLES (
  ID uuid PRIMARY KEY,
  DISCOUNT DECIMAL(7,2) NOT NULL
);

CREATE TABLE BUNDLE_PRODUCTS (
  BUNDLE_ID uuid REFERENCES BUNDLES (ID),
  PRODUCT_ID uuid REFERENCES PRODUCTS(ID),
  PRIMARY KEY(BUNDLE_ID, PRODUCT_ID)
);
